### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by josephtkim** [klaurenjerchau/prj-rev-bwfs-dasmoto#6]
**Grade: Meets Expectations**

**Summary:** Overall, I think you did a good job with your project implementation. Your project design appears identical to the specification, and your code seems to follow the structure of the webpage correctly. 

There are a few areas of improvement here. First, it is always a good idea to separate each section of the content into div elements, which signify divisions. Next, tags must be properly closed, with the innermost tags being closed first, before closing the outer tags. Next, there are some formatting improvements needed for your CSS code, which is detailed in the Issues. Finally, try to simplify the code for shared properties in the CSS.

As a further challenge, consider adding responsive design to your page. This might take some extra research, but can be a great way to learn and apply an important web design tool and concepts. Based on your work so far, I think you are up for the challenge. 

Keep up the good work!

**Comment by klaurenjerchau** [comment]
Thank you!!! I appreciate all of your constructive feedback it is all very helpful.
